#ifndef FACEMARKLBF_GLOBAL_H
#define FACEMARKLBF_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FACEMARKLBF_LIBRARY)
#  define FACEMARKLBFSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FACEMARKLBFSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FACEMARKLBF_GLOBAL_H
